'use strict';
/*
 * Weekly revenue report - generating and sending it  (Nova)
 * ---------------------------------------------------------
 * One function, used by two callers: the Monday cron in jobs/revenueReport.js
 * and the "Send it now" button in routes/revenue.js. They share this so a
 * manual send is provably the same document the schedule would have sent -
 * if the two ever diverged, testing the button would stop meaning anything.
 *
 * Every attempt writes a cs_report_runs row, successful or not. A report that
 * quietly fails to send on a Monday morning is indistinguishable from one
 * nobody opened, which is exactly the failure this company has had before.
 *
 * NOTE: no backtick/template-literal strings are used anywhere in this file
 * (Windows-safe per the Nova editing rules).
 */

var { pool } = require('../db');
var CSV = require('./revenueCsv');
var RR = require('./revenueReport');
var PDF = require('./revenuePdf');
var SET = require('./revenueSettings');
var { sendEmail, emailTemplate } = require('./email');

function money(n) { return PDF.money(n, false); }

function deltaWord(p) {
  if (p === null || p === undefined || !isFinite(p)) return 'no prior week to compare';
  var v = Math.round(p * 10) / 10;
  if (v > 0) return 'up ' + v.toFixed(1) + '% on the week before';
  if (v < 0) return 'down ' + Math.abs(v).toFixed(1) + '% on the week before';
  return 'flat on the week before';
}

function daysBetween(aYmd, bYmd) {
  var a = new Date(aYmd + 'T00:00:00Z').getTime();
  var b = new Date(bYmd + 'T00:00:00Z').getTime();
  return Math.round((b - a) / 86400000);
}

function buildEmailHtml(report, history, staleNote) {
  var c = report.company.cards;
  var details = [
    { label: 'Week', value: PDF.weekLabel(report.window.last) },
    { label: 'Total revenue', value: money(c.total.value) }
  ];
  RR.CLASSES.forEach(function (cls) {
    details.push({ label: report.meta.classLabels[cls], value: money(c[cls].value) });
  });
  details.push({ label: 'Calls', value: String(report.company.weeks[report.window.last].calls) });
  details.push({ label: 'Locations', value: String(report.locations.length) });

  var body = 'Total revenue for the week was <strong>' + money(c.total.value) + '</strong>, ' +
    deltaWord(c.total.d_prior) + '. The attached PDF has a page per location with ' +
    report.window.count + ' weeks of history, broken into Roadside, Battery and Locksmith.';
  if (staleNote) body += '<br><br><strong style="color:#b91c1c">' + staleNote + '</strong>';

  return emailTemplate({
    badge: 'Weekly Revenue',
    badgeColor: c.total.d_prior !== null && c.total.d_prior < 0 ? 'red' : 'green',
    title: 'Revenue for ' + PDF.weekLabel(report.window.last),
    body: body,
    details: details,
    footerNote: 'Generated by Nova from the CallSearch export. Figures restate as late payments post, ' +
      'so a prior week can move.'
  });
}

/*
 * Build the report, render it, email it, log the run.
 *
 * opts:
 *   endWeek      override the latest week (defaults to the last complete one)
 *   send         false to build without emailing (the page preview uses this)
 *   triggeredBy  'schedule' | 'manual'
 *   to           override the recipient list (a test send to one person)
 *
 * Resolves { report, pdf, filename, recipients, sent, stale, run_id }.
 * Rejects only when the report itself cannot be built; a failed SEND resolves
 * with sent:false and is recorded, because the PDF is still good and the
 * caller may well want to hand it over anyway.
 */
async function generate(opts) {
  opts = opts || {};
  var cfg = await SET.all();
  var report = await RR.buildReport(pool, {
    endWeek: opts.endWeek,
    weeks: opts.weeks || cfg.weeks,
    locationMap: cfg.locationMap,
    today: opts.today
  });
  var history = await RR.historySummary(pool);

  // Staleness. Ingest is a manual drop, so "nobody uploaded anything" is the
  // expected failure and it has to be said out loud - on a chart it looks
  // identical to a week where the company earned nothing.
  var stale = null;
  var today = opts.today || new Date().toISOString().slice(0, 10);
  if (!history.last_date) {
    stale = 'No CallSearch export has ever been imported, so this report is empty.';
  } else {
    var age = daysBetween(history.last_date, today);
    if (age > cfg.staleDays) {
      stale = 'The newest call in Nova is from ' + history.last_date + ', ' + age +
        ' days ago. Import a fresh CallSearch export - these figures are out of date.';
    }
  }

  var pdf = await PDF.buildPdf(report);
  var filename = PDF.fileName(report);

  var to = opts.to ? SET.cleanEmails(opts.to) : cfg.recipients;
  var sent = false, error = null;

  if (opts.send !== false) {
    if (!to.length) {
      error = 'No recipients are configured for the weekly revenue report.';
    } else {
      try {
        sent = await sendEmail(
          to,
          'Weekly revenue - ' + PDF.weekLabel(report.window.last),
          buildEmailHtml(report, history, stale),
          null,
          [{ filename: filename, content: pdf.toString('base64') }]
        );
        if (!sent) error = 'Resend did not accept the message (see the server log).';
      } catch (e) {
        error = e && e.message ? e.message : String(e);
      }
    }
  }

  var runId = null;
  try {
    var r = await pool.query(
      'INSERT INTO cs_report_runs (week_end, weeks, locations, revenue_total, recipients, bytes, ok, error, triggered_by) ' +
      'VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',
      [
        CSV.addDays(report.window.last, 6),
        report.window.count,
        report.locations.length,
        report.company.cards.total.value,
        to.join(', '),
        pdf.length,
        opts.send === false ? true : sent,
        error,
        opts.triggeredBy || 'manual'
      ]
    );
    runId = r.rows[0].id;
  } catch (e) {
    // The log is not the deliverable. A failure to record the run must not
    // swallow a PDF that was built and emailed successfully.
    console.error('[revenue] could not record report run: ' + (e && e.message));
  }

  return {
    report: report,
    history: history,
    pdf: pdf,
    filename: filename,
    recipients: to,
    sent: sent,
    stale: stale,
    error: error,
    run_id: runId
  };
}

module.exports = { generate: generate, buildEmailHtml: buildEmailHtml, deltaWord: deltaWord };
